### ISSUE TITLE
clean architectureについてまとめて終礼で発表してください

### ISSUE THREAD

**Issue by kozukaaaa** [kobashou06/practice-xml-parse#5]
詳しくは藤さんに聞くといいです

**Comment by kobayashota** [comment]
発表予定は4/19, 予備日を4/20とさせてください。

**Comment by kobayashota** [comment]
4/19発表資料
https://docs.google.com/spreadsheets/d/1whOZ6x_tfBjwjZKHqRKS0nJJ4qdwcM1ft4eOhrOynSQ/edit#gid=0

4/20の発表は

- clean architecture
- MVVM

について掘り下げて調べて発表予定です🙇‍♀️

**Comment by kobayashi-shota** [comment]
4/20発表資料
https://docs.google.com/presentation/d/1ZUG9x-SlLxqGapsX4yBuMXyqU1Qnf76NUbdGPzH33QU/edit#slide=id.gd31cc36253_0_25

MVVMについてはまとめる余裕がなかったため、個人的に調査を続けていきます🙇‍♀️

**Comment by kozukaaaa** [comment]
doneのためクローズします

**Comment by kobayashi-shota** [comment]
ありがとうございます🙇‍♂️

2021年4月21日(水) 16:53 kozukaaaa ***@***.***>:
