### ISSUE TITLE
WebViewが閉じない問題

### ISSUE THREAD

**Issue by kobayashota** [kobashou06/practice-xml-parse#7]
### 概要

#3 の対応中に発生した問題。

現状iPod Touch(7th generation)にて確認されている。

### 対応予定

WebViewController周りの調査を行う

### 対応完了予定

2021/04/26(予備日 2021/04/27)

### 参考資料

https://user-images.githubusercontent.com/67745523/116017654-311b6800-a67b-11eb-8d34-6a70c681d29a.mp4

**Comment by kobayashota** [comment]
## 変更点

- WebViewControllerへ、Modalでの画面遷移を廃止
- NavigationControl のPushで画面遷移するように変更
    - 前の画面に戻れないバグが解消された

## キャプチャ

https://user-images.githubusercontent.com/67745523/116172043-f4b43e80-a744-11eb-8d94-05f11c607f46.MP4

**Comment by kobayashota** [comment]
追加改修目的

- リスト画面のNavigationBarを消去する
- WebViewControllerはModalのまま閉じる導線を追加する

**Comment by kozukaaaa** [comment]
確認しました

* リスト画面のNavigationBarを消去する
* WebViewControllerはModalのまま閉じる導線を追加する

で改修お願いします

**Comment by kobayashota** [comment]
## キャプチャ

https://user-images.githubusercontent.com/67745523/116182680-a6f50180-a757-11eb-8e73-50489bdbd15f.MP4
